version: '3.7'

services:

  # ===================== ELASTICSEARCH =====================
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    container_name: es-demo
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
    networks:
      - elk-net

  # ===================== KIBANA =====================
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.16
    container_name: kibana-demo
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elk-net
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro

  # ===================== LOGSTASH =====================
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.16
    container_name: logstash-demo
    environment:
      - LS_JAVA_OPTS=-Xmx512m -Xms512m
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      # Application and web logs
      - ./php-app/logs:/var/log/phpapp:ro            # upload.log, access.log
      - ./logs/apache:/var/log/apache2:ro            # Apache logs
      - ./modsec/logs:/var/log/waf:ro                # ModSecurity logs
    depends_on:
      - elasticsearch
    networks:
      - elk-net

  # ===================== PHP + APACHE WEB APP =====================
  phpapp:
    build: ./php-app
    container_name: php-web
    volumes:
      - ./php-app:/var/www/html                      # app source code (index.php, uploads/)
      - ./php-app/logs:/var/www/html/logs            # forensic logs
      - ./logs/apache:/var/log/apache2               # Apache logs (access/error)
    expose:
      - "80"
    networks:
      - elk-net

  # ===================== MODSECURITY (WAF FRONTEND) =====================
  modsec-waf:
    user: root
    image: owasp/modsecurity-crs:nginx
    container_name: modsec-waf
    environment:
      - PARANOIA=1
      - PROXY=1
      - BACKEND=http://phpapp:80                     # Send filtered traffic to PHP app
    volumes:
      - ./modsec/logs:/var/log/modsecurity           # store audit logs here
      - ./modsec/custom-rules:/etc/modsecurity.d/custom-rules.conf:ro
      - ./modsec/modsecurity.conf:/etc/nginx/templates/modsecurity.d/modsecurity.conf.template:ro
    depends_on:
      - phpapp
    ports:
      - "8080:8080"                                   # entry point for external traffic
    networks:
      - elk-net
    # command: ["/usr/sbin/nginx", "-g", "daemon off;"]

volumes:
  esdata:

networks:
  elk-net:
    name: elk-net
    driver: bridge
